[package]
name = "prog-utils"
version = "0.0.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
ariadne = { workspace = true }

serde = { workspace = true, optional = true }