[package]
name = "prog-utils"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ariadne = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }