[package]
name = "prog-lang"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]
api = [
	"serde",
	"prog-parser/serde",
	"prog-interpreter/serde",
	"prog-utils/serde",
	"dep:actix-web",
	"dep:actix-cors",
	"dep:env_logger"
]
website = ["api", "dep:actix-files"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.82"
ariadne = "0.4.1"
serde_json = "1.0.116"
pest = "2.7.9"
pest_derive = "2.7.9"
prog-parser = { path = "./crates/prog-parser" }
prog-interpreter = { path = "./crates/prog-interpreter" }
prog-utils = { path = "./crates/prog-utils" }
prog-macros = { path = "./crates/prog-macros" }
serde = { version = "1.0.199", features = ["derive"] }

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.5.4", features = ["derive"] }
pest = { workspace = true }
anyhow = { workspace = true }
prog-parser = { workspace = true }
prog-interpreter = { workspace = true }
prog-utils = { workspace = true }

serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
actix-web = { version = "4", optional = true }
actix-cors = { version = "0.7.0", optional = true }
actix-files = { version = "0.6.5", optional = true }
env_logger = { version = "0.11.3", optional = true }