[package]
name = "prog-lang"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.82"
ariadne = "0.4.1"
prog-parser = { path = "./crates/prog-parser" }
prog-interpreter = { path = "./crates/prog-interpreter" }
prog-utils = { path = "./crates/prog-utils" }
prog-macros = { path = "./crates/prog-macros" }

[dependencies]
actix-web = "4"
actix-cors = "0.7.0"
actix-files = "0.6.5"
serde = "1.0.199"
serde-error = "0.1.2"
serde_json = "1.0.116"
clap = { version = "4.5.4", features = ["derive"] }
anyhow = { workspace = true }
prog-parser = { workspace = true }
prog-interpreter = { workspace = true }
prog-utils = { workspace = true }
