[package]
name = "prog-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2 = "*"
paste = "1.0.14"
syn = { version = "*", features = ["full", "extra-traits"] }