[package]
name = "prog-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
quote = "*"
proc-macro2 = "*"
paste = "1.0.14"