[package]
name = "prog-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
proc-macro2 = "1.0.92"
syn = { version = "2.0.91", features = ["full", "extra-traits"] }