name: Build

on:
  push:
  pull_request:
    branches: [main, experimental]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Test
        run: |
          cargo check
          cargo test --all
      
      - name: Test all features
        run: |
          cargo install cargo-all-features
          cargo test-all-features

      - name: Build
        run: |
          cargo build --release
      
      - name: Clippy test
        run: cargo clippy